#!/usr/bin/env python3
"""Demo data for a fictional user, Sam: an indie developer shipping a side project (Loaflog, a sourdough bake log
app), learning guitar for an open mic, and doing a seasonal closet clear-out. Every date is an offset from one day
and every time is a wall-clock time in the configured timezone, so the story always reads as "now". Stdlib only.

The single source of example data: docs/seed.example.json and mobile/mock/extra.json are generated by `mock`;
never export a hub or database and edit the result.

  seed      --day D --timezone TZ --language L --app-name NAME --morning-at HH:MM --evening-at HH:MM --out FILE
            a seed file for a real hub (MOJITO_SEED): goals, plans, items, history, projects, settings
  mock      the same options with --seed-out FILE --extra-out FILE instead of --out
            the data of the mock server (mobile: npm run mock), which shifts it to its own today
  build     the same options with --port N --public-url URL --fcm-credentials PATH|placeholder --out DIR
            a demo hub instance: seed, calendar, tokens, hub.env and the clients' env files
  load      --out DIR    hub running, no device registered yet: history goes in through the API
  backdate  --out DIR    hub stopped: that history moves to its story time; saves golden/
  reset     --out DIR    hub stopped: back to golden/ (before every take)
  ask       --out DIR    hub running: one feedback waiting for your approval

D is YYYY-MM-DD or "today" (in TZ); TZ is an IANA zone, the hub's MOJITO_TIMEZONE; L is zh or en.
"""
import argparse
import hashlib
import json
import re
import secrets
import shutil
import sqlite3
import stat
import subprocess
import urllib.error
import urllib.request
from datetime import UTC, date, datetime, time, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

ROLES = ("app", "worker", "agent", "maintainer", "source:cards")
AGENT = "server-agent"  # the hub's source name for the server agent (auth.py SOURCE_OF)
OWNER_NAME = "Sam"
CONTACT_EMAIL = "sam@example.com"


# ---------------------------------------------------------------- time and language

class Clock:
    """Day offsets from the story's today; times are wall-clock times in `tz`."""

    def __init__(self, day: date, tz: ZoneInfo):
        self.day, self.tz = day, tz

    def at(self, n: int, hm: str) -> datetime:
        h, m = hm.split(":")
        return datetime.combine(self.day + timedelta(days=n), time(int(h), int(m)), self.tz)

    def iso(self, n: int, hm: str) -> str:
        return self.at(n, hm).isoformat(timespec="seconds")

    def ymd(self, n: int) -> str:
        return (self.day + timedelta(days=n)).isoformat()


class Lang:
    """t(zh, en) picks the text of the chosen UI language (settings.language)."""

    def __init__(self, language: str):
        if language not in ("zh", "en"):
            raise SystemExit(f"--language must be zh or en, got {language!r}")
        self.language = language

    def __call__(self, zh: str, en: str) -> str:
        return zh if self.language == "zh" else en


def hm_plus(hm: str, minutes: int) -> str:
    h, m = hm.split(":")
    total = int(h) * 60 + int(m) + minutes
    if total >= 24 * 60:
        raise SystemExit(f"{hm} + {minutes} min passes midnight; pick an earlier --evening-at")
    return f"{total // 60:02d}:{total % 60:02d}"


def db_ts(dt: datetime) -> str:
    """The hub's stored format (db.ts): UTC ISO-8601, second precision."""
    return dt.astimezone(UTC).isoformat(timespec="seconds")


def sha7(text: str) -> str:
    return hashlib.sha1(text.encode()).hexdigest()[:7]


def slug_of(app_name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", app_name.lower()).strip("-")


# ---------------------------------------------------------------- the story: seed

def seed_of(c: Clock, t: Lang, app: str, morning_at: str, evening_at: str) -> dict:
    slug = slug_of(app)
    goals = [
        {"id": "g-launch", "title": t("上线 Loaflog 1.0", "Ship Loaflog 1.0"), "status": "active"},
        {"id": "g-openmic", "title": t("在开放麦上弹完三首歌", "Play three songs at the open mic"), "status": "active"},
        {"id": "g-closet", "title": t("换季整理：清出两袋衣服捐掉", "Seasonal clear-out: donate two bags of clothes"),
         "status": "active"},
    ]
    projects = [
        {"id": "p-loaflog", "title": "Loaflog", "area": "research", "repo_path": "~/code/loaflog", "goal_id": "g-launch"},
        {"id": "p-app", "title": app, "area": "research", "repo_path": f"~/code/{slug}", "goal_id": None},
        {"id": "p-guitar", "title": t("学吉他", "Guitar"), "area": "life", "repo_path": None, "goal_id": "g-openmic"},
        {"id": "p-closet", "title": t("换季整理", "Closet clear-out"), "area": "life", "repo_path": None, "goal_id": "g-closet"},
    ]

    def item(id_, title, category, status, next_step, next_at, owner, done, goal, progress, updated, by):
        return {"id": id_, "title": title, "category": category, "status": status, "next_step": next_step,
                "next_at": next_at, "owner": owner, "done_definition": done, "goal_id": goal,
                "progress": progress, "updated_at": updated, "updated_by": by}

    finished = t("已完成", "Done")
    items = [
        # today (Focus): 14:00, 19:00, 21:00, plus the nearest later one (tomorrow 09:00)
        item("i-lf-onboarding", t("Loaflog：新手引导", "Loaflog: onboarding"), "research", "active",
             t("把引导页砍到 3 屏，录一段走查视频", "Cut onboarding to three screens and record a walkthrough"),
             c.iso(0, "14:00"), "me", t("你把新引导发给内测用户", "You ship the new onboarding to beta testers"),
             "g-launch", None, c.iso(-1, "21:53"), AGENT),
        item("i-gt-practice", t("吉他：练习 20 分钟", "Guitar: 20-minute practice"), "life", "active",
             t("G–C–D 换和弦慢练（节拍器 60），再过一遍第二首的副歌",
               "Slow G–C–D changes at 60 bpm, then the chorus of song two"),
             c.iso(0, "19:00"), "me", t("你练满 20 分钟并记下卡住的地方", "You practise 20 minutes and note where you got stuck"),
             "g-openmic", None, c.iso(-1, "21:53"), AGENT),
        item("i-cl-sort", t("换季：整理夏装", "Closet: sort the summer clothes"), "life", "active",
             t("装满一袋捐赠、一箱收纳", "Fill one donation bag and one storage box"),
             c.iso(0, "21:00"), "me", t("你装好两袋要捐的衣服", "You pack two bags for donation"),
             "g-closet", {"value": 1, "target": 2, "unit": t("袋", "bags")}, c.iso(-2, "20:41"), "worker"),
        item("i-lf-landing", t("Loaflog：落地页文案", "Loaflog: landing page copy"), "research", "active",
             t("列出三条功能介绍的要点", "List the points for the three feature blurbs"),
             c.iso(1, "09:00"), "me", t("你把落地页文案发给设计师 Riley", "You send the landing page copy to Riley, the designer"),
             "g-launch", None, c.iso(-1, "21:53"), AGENT),
        # later this period
        item("i-lf-pricing", t("Loaflog：定价", "Loaflog: pricing"), "research", "active",
             t("对照内测问卷，比较买断和年订阅", "Compare one-time vs. yearly against the beta survey"),
             c.iso(2, "10:00"), "me", t("你定下价格并写进商店页草稿", "You settle the price and put it in the store listing draft"),
             "g-launch", None, c.iso(-3, "09:10"), AGENT),
        item("i-app-today", t(f"{app}：今天页只留我要看的", f"{app}: trim the Today page"), "research", "active",
             t("在对话里说一句要隐藏哪些区块", "Say in chat which blocks to hide"),
             c.iso(3, "21:00"), "me", t("你看到新版今天页", "You see the new Today page"),
             None, None, c.iso(-2, "22:10"), AGENT),
        item("i-gt-song3", t("吉他：学第三首歌", "Guitar: learn song three"), "life", "active",
             t("选好歌，打印和弦谱", "Pick the song and print the chord sheet"),
             c.iso(4, "20:00"), "me", t("你能不停顿弹完第三首", "You play song three start to finish without stopping"),
             "g-openmic", {"value": 2, "target": 3, "unit": t("首", "songs")}, c.iso(-4, "21:20"), "worker"),
        item("i-cl-donate", t("换季：送捐赠衣物", "Closet: drop off the donations"), "life", "active",
             t("顺路确认捐赠点的开放时间", "Check the drop-off hours on the way"),
             c.iso(5, "11:00"), "me", t("你把两袋衣服送到捐赠点", "You drop both bags at the donation point"),
             "g-closet", None, c.iso(-4, "21:20"), "worker"),
        # the Overdue (amber), Gone quiet (red) and Your call blocks
        item("i-lf-crash", t("修复上传照片闪退", "Fix the photo-upload crash"), "research", "active",
             t("等夜间测试跑完，看一眼崩溃率", "Let the overnight test finish, then check the crash rate"),
             c.iso(-2, "18:00"), "auto_then_me", t("你确认崩溃率降到 0.1% 以下", "You confirm the crash rate is under 0.1%"),
             "g-launch", {"value": 31, "target": 40, "unit": t("轮测试", "test runs")}, c.iso(-1, "09:00"), "worker"),
        item("i-gt-strings", t("吉他：换琴弦", "Guitar: restring"), "life", "active",
             t("买一套细弦", "Buy a set of light strings"),
             None, "me", t("你换好琴弦并调好音", "You restring and tune the guitar"),
             "g-openmic", None, c.iso(-5, "08:11"), "worker"),
        item("i-lf-beta-date", t("定内测截止日", "Pick the beta cut-off date"), "research", "waiting_you",
             t("给三位核心内测用户发个日期投票", "Send a date poll to the three lead beta testers"),
             c.iso(3, "12:00"), "me", t("你收到三个人都确认的日期", "All three confirm a date"),
             "g-launch", None, c.iso(-1, "12:20"), AGENT),
        # done in the previous period
        item("i-prev-signup", t("Loaflog：注册流程", "Loaflog: sign-up flow"), "research", "done", finished,
             None, "me", t("你把注册流程发给内测用户", "You ship the sign-up flow to beta testers"),
             "g-launch", None, c.iso(-7, "17:30"), "app"),
        item("i-prev-song1", t("吉他：完整弹完第一首", "Guitar: song one start to finish"), "life", "done", finished,
             None, "me", t("你不停顿弹完第一首", "You play song one without stopping"),
             "g-openmic", None, c.iso(-6, "09:30"), "app"),
        item("i-prev-shoes", t("换季：鞋柜", "Closet: shoe rack"), "life", "done", finished,
             None, "me", t("你清出不穿的鞋", "You clear out the shoes you don't wear"),
             "g-closet", None, c.iso(-6, "21:48"), "app"),
    ]
    item_projects = {
        "i-lf-onboarding": "p-loaflog", "i-lf-landing": "p-loaflog", "i-lf-pricing": "p-loaflog", "i-lf-crash": "p-loaflog",
        "i-lf-beta-date": "p-loaflog", "i-prev-signup": "p-loaflog", "i-app-today": "p-app",
        "i-gt-practice": "p-guitar", "i-gt-song3": "p-guitar", "i-gt-strings": "p-guitar", "i-prev-song1": "p-guitar",
        "i-cl-sort": "p-closet", "i-cl-donate": "p-closet", "i-prev-shoes": "p-closet",
    }
    goal_ids = [g["id"] for g in goals]
    plans = [
        {"id": f"p-{c.ymd(-18)}", "start": c.ymd(-18), "end": c.ymd(-5), "goal_ids": goal_ids,
         "item_ids": ["i-prev-signup", "i-prev-song1", "i-prev-shoes", "i-lf-pricing"], "status": "closed",
         "created_at": c.iso(-19, "21:30"), "closed_at": c.iso(-4, "00:01")},
        {"id": f"p-{c.ymd(-4)}", "start": c.ymd(-4), "end": c.ymd(9), "goal_ids": goal_ids,
         "item_ids": ["i-lf-onboarding", "i-lf-landing", "i-lf-pricing", "i-lf-crash", "i-lf-beta-date", "i-app-today",
                      "i-gt-practice", "i-gt-song3", "i-gt-strings", "i-cl-sort", "i-cl-donate"],
         "status": "active", "created_at": c.iso(-5, "21:20"), "closed_at": None},
    ]
    return {"demo_day": c.ymd(0), "goals": goals, "plans": plans, "items": items,
            "records": records_of(c, t, morning_at, evening_at), "projects": projects, "item_projects": item_projects,
            "settings": {"morning_at": morning_at, "evening_at": evening_at, "evening_enabled": True,
                         "language": t.language}}


def records_of(c: Clock, t: Lang, morning_at: str, evening_at: str) -> list[dict]:
    """Evening questions at evening_at with replies minutes later (5 of the last 6 answered), two morning briefs."""
    out = []
    e = lambda minutes: hm_plus(evening_at, minutes)  # noqa: E731

    def rec(n, hm, author, source, kind, tier, item_id, title, body):
        out.append({"id": f"r-demo-{len(out) + 1:02d}", "at": c.iso(n, hm), "author": author, "source": source,
                    "kind": kind, "tier": tier, "item_id": item_id, "title": title, "body": body,
                    "evidence": None, "needs_processing": False})

    def ask(n):  # agent texts.py evening_title / evening_body
        rec(n, evening_at, "system", AGENT, "chat", "digest", None,
            t("今天推进了什么？", "What did you move forward today?"),
            t("回复这条就是今天的笔记，一两句就行。", "Your reply becomes today's note. A sentence or two is enough."))

    def me_chat(n, hm, text):
        rec(n, hm, "me", "app", "chat", "log", None, text[:40], text)

    def agent_chat(n, hm, text):
        rec(n, hm, "system", AGENT, "chat", "digest", None, text.splitlines()[0][:40], text)

    def note(n, hm, item_id, text):
        rec(n, hm, "me", "app", "note", "log", item_id, text[:40], text)

    ask(-6)
    me_chat(-6, e(17), t("注册流程的最后一个 bug 修完了，第一首歌也能完整弹下来了",
                         "Fixed the last sign-up bug, and I can play song one all the way through"))
    agent_chat(-6, e(18), t("记下了，两件事都往前走了一步。\n\n- **Loaflog：注册流程**：明天发给内测用户就能收尾\n"
                            "- **吉他**：第一首完成，下一步开始第二首的副歌",
                            "Noted, both moved forward.\n\n- **Loaflog: sign-up flow**: ship it to beta testers tomorrow "
                            "and it's done\n- **Guitar**: song one is done; next, the chorus of song two"))

    strings = t("练琴时发现一弦老是跑音，可能该换弦了", "The high E keeps going out of tune, probably time for new strings")
    note(-5, "08:10", "i-gt-strings", strings)
    rec(-5, "08:11", "system", "worker", "log", "log", "i-gt-strings",
        t("由笔记记成事项：吉他：换琴弦", "Note became an item: Guitar: restring"),
        t(f"来自笔记「{strings}」", f"From note “{strings}”"))
    ask(-5)
    me_chat(-5, e(28), t("复盘写完了，下一期把定价放前面", "Review done. Next period, pricing goes first"))
    agent_chat(-5, e(29), t("好，下一期按你说的排：**Loaflog：定价**放在第一周。",
                            "OK, the next period follows that: **Loaflog: pricing** is in week one."))

    ask(-4)
    me_chat(-4, e(35), t("引导页改了一半，夏装还没动", "Onboarding is half redone; haven't touched the summer clothes yet"))
    agent_chat(-4, e(36), t("记下了。\n\n- **Loaflog：新手引导**：先把 5 屏合成 3 屏，再录视频\n"
                            "- **换季：整理夏装**：挪到工作日的一个晚上，一次装一袋",
                            "Noted.\n\n- **Loaflog: onboarding**: merge the five screens into three first, then record "
                            "the video\n- **Closet: sort the summer clothes**: moved to a weeknight, one bag at a time"))

    note(-3, "13:20", "i-lf-crash", t("旧手机上一次选 10 张以上照片就闪退，内存峰值很高",
                                      "On older phones, picking more than 10 photos crashes the app; memory spikes"))
    ask(-3)  # left unanswered: the metrics show 5 of 6

    agent_chat(-2, morning_at, t("今天先让夜间测试跑起来\n\n**今天日程**\n- 16:00 和 Casey 通话：内测反馈\n\n**今日重点**\n"
                                 "Loaflog：\n- 修复上传照片闪退 —— 下一步：开始夜间测试，今天 18:00\n\n"
                                 "学吉他：\n- 吉他：练习 20 分钟 —— 下一步：G–C–D 换和弦慢练，还有 2 天\n\n信息流新增 4 张。",
                                 "Start the overnight test today\n\n**Today's schedule**\n- 16:00 Call with Casey: beta "
                                 "feedback\n\n**Focus**\nLoaflog:\n- Fix the photo-upload crash — next: start the overnight "
                                 "test, today 18:00\n\nGuitar:\n- Guitar: 20-minute practice — next: slow G–C–D changes, "
                                 "in 2 days\n\n4 new in Feed."))
    note(-2, "20:40", "i-cl-sort", t("夏装里有三件还想留，其他都可以捐", "Keeping three summer pieces; the rest can go"))
    ask(-2)
    me_chat(-2, e(11), t("夜间测试开始跑了，晚上练了 20 分钟琴", "Overnight test is running; practised guitar for 20 minutes"))
    agent_chat(-2, e(12), t("记下了。\n\n- **修复上传照片闪退**：先让它跑着，明晚看崩溃率\n"
                            "- **吉他**：这周练了 3 次，换和弦明显顺了",
                            "Noted.\n\n- **Fix the photo-upload crash**: let it run; check the crash rate tomorrow night\n"
                            "- **Guitar**: third practice this week; the chord changes are getting smoother"))

    agent_chat(-1, morning_at, t("今天把新手引导改完\n\n**今天日程**\n- 12:30 和 Jordan 吃午饭\n\n**今日重点**\n"
                                 "Loaflog：新引导还差最后一屏。\n"
                                 "- Loaflog：新手引导 —— 下一步：把 5 屏合成 3 屏，今天 14:00\n\n"
                                 "**逾期 1 件**：修复上传照片闪退\n\n信息流新增 5 张。",
                                 "Finish the new onboarding today\n\n**Today's schedule**\n- 12:30 Lunch with Jordan\n\n"
                                 "**Focus**\nLoaflog: the new onboarding is one screen short.\n"
                                 "- Loaflog: onboarding — next: merge five screens into three, today 14:00\n\n"
                                 "**Overdue: 1** Fix the photo-upload crash\n\n5 new in Feed."))
    note(-1, "12:15", "i-lf-beta-date", t("Casey 下下周出差，内测截止最好定在那之前",
                                          "Casey travels the week after next, so the beta cut-off should come before that"))
    ask(-1)
    me_chat(-1, e(22), t("引导合成了 3 屏，还差录视频；练了琴", "Onboarding is down to three screens; the video is left. Practised guitar"))
    agent_chat(-1, e(23), t("记下了。明天先录走查视频，再发给内测。\n\n"
                            "- **Loaflog：新手引导**：下一步改成「把引导页砍到 3 屏，录一段走查视频」，明天 14:00\n"
                            "- **吉他**：这周练了 4 次，明天 19:00 再练 20 分钟",
                            "Noted. Tomorrow: record the walkthrough, then ship it to beta.\n\n"
                            "- **Loaflog: onboarding**: next step is now “Cut onboarding to three screens and record a "
                            "walkthrough”, tomorrow 14:00\n"
                            "- **Guitar**: 4 sessions this week; 20 more minutes tomorrow at 19:00"))
    # dates in texts are relative ("tomorrow"): the mock server shifts timestamps, never text
    rec(-1, e(23), "system", AGENT, "log", "log", "i-lf-onboarding",
        t("Loaflog：新手引导：下一步 从 把 5 屏合成 3 屏 改成 把引导页砍到 3 屏，录一段走查视频",
          "Loaflog: onboarding: Next step: Merge five screens into three → Cut onboarding to three screens and record "
          "a walkthrough"), "")
    return out


# ---------------------------------------------------------------- the story: everything that arrives through the API

def calendar_of(c: Clock, t: Lang) -> list[dict]:
    """Wall-clock events in the configured timezone (demo-coffee was added from chat, see mock records)."""
    def ev(uid, n, start, end, title, location, rrule):
        return {"uid": uid, "start": c.at(n, start), "end": c.at(n, end), "all_day": False, "title": title,
                "location": location, "rrule": rrule}

    return [
        ev("demo-cowork", 0, "09:30", "11:30", t("共享办公", "Coworking"), t("图书馆二楼", "Library, 2nd floor"), None),
        ev("demo-lunch", 0, "12:30", "13:15", t("和 Jordan 吃午饭", "Lunch with Jordan"), None, None),
        ev("demo-icons", 0, "16:00", "16:30", t("和 Riley 过图标（视频）", "Icon review with Riley (video)"), None, None),
        {"uid": "demo-freeze", "start": c.at(1, "00:00"), "end": c.at(2, "00:00"), "all_day": True,
         "title": t("内测版本冻结", "Beta build freeze"), "location": None, "rrule": None},
        ev("demo-coffee", 1, "10:00", "10:30", t("和 Jordan 喝咖啡", "Coffee with Jordan"), None, None),
        ev("demo-lesson", 2, "18:30", "19:30", t("吉他课", "Guitar lesson"), t("音乐教室 3 号房", "Music school, room 3"),
           "FREQ=WEEKLY;COUNT=8"),
        ev("demo-casey", 3, "11:00", "11:45", t("和 Casey 通话：内测反馈", "Call with Casey: beta feedback"), None, None),
        ev("demo-signup", 5, "18:00", "18:30", t("开放麦报名截止", "Open mic sign-up closes"), t("街角咖啡馆", "Corner café"), None),
    ]


def ics_of(c: Clock, t: Lang) -> str:
    fmt = "%Y%m%dT%H%M%SZ"
    stamp = datetime.now(UTC).strftime(fmt)
    lines = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//demo//sam//EN"]
    for e in calendar_of(c, t):
        lines += ["BEGIN:VEVENT", f"UID:{e['uid']}@demo.invalid", f"DTSTAMP:{stamp}"]
        if e["all_day"]:
            lines += [f"DTSTART;VALUE=DATE:{e['start']:%Y%m%d}", f"DTEND;VALUE=DATE:{e['end']:%Y%m%d}"]
        else:
            lines += [f"DTSTART:{e['start'].astimezone(UTC).strftime(fmt)}", f"DTEND:{e['end'].astimezone(UTC).strftime(fmt)}"]
        lines.append(f"SUMMARY:{e['title']}")
        if e["location"] is not None:
            lines.append(f"LOCATION:{e['location']}")
        if e["rrule"] is not None:
            lines.append(f"RRULE:{e['rrule']}")
        lines.append("END:VEVENT")
    lines.append("END:VCALENDAR")
    return "\r\n".join(lines) + "\r\n"


def paper(t: Lang, what: str, why: str, project_title: str | None) -> str:
    summary = t(f"{what}\n为什么你会感兴趣：{why}", f"{what}\nWhy it may interest you: {why}")
    return summary if project_title is None else summary + t(f"\n相关项目：{project_title}", f"\nRelated project: {project_title}")


def brief_body(t: Lang) -> str:
    """Today's AI brief in the worker's layout (worker reports._brief_body): one line per item, the link text names the
    source, papers as "what / for you"."""
    none = t("今天没有", "Nothing today")
    return "\n\n".join([
        t("## 新模型发布", "## New models"),
        t("- MobileNetV4：面向手机的通用骨干网络，在多种手机芯片上又快又准。 [arXiv](https://arxiv.org/abs/2404.10518)",
          "- MobileNetV4: a general backbone for phones, fast and accurate across many phone chips. "
          "[arXiv](https://arxiv.org/abs/2404.10518)"),
        t("## 重要论文", "## Papers"),
        t("- [SAM 2: Segment Anything in Images and Videos](https://arxiv.org/abs/2408.00714)：把按提示分割扩展到视频，"
          "能跨帧跟住同一个物体。 和你有关：Loaflog 可以从转一圈的短视频里挑最清楚的切面来打分。",
          "- [SAM 2: Segment Anything in Images and Videos](https://arxiv.org/abs/2408.00714): extends promptable "
          "segmentation to video and follows one object across frames. For you: Loaflog could pick the clearest crumb "
          "shot from a short turn-around video."),
        t("## 开源项目", "## Open source"),
        t("- ExecuTorch：PyTorch 的端侧推理运行时，训练好的模型可以直接部署到 iOS 和 Android。 "
          "[GitHub](https://github.com/pytorch/executorch)",
          "- ExecuTorch: PyTorch's on-device runtime; a trained model deploys straight to iOS and Android. "
          "[GitHub](https://github.com/pytorch/executorch)"),
        t("## 行业新闻", "## Industry news"),
        none,
        t("## 趋势解读", "## Trends"),
        t("端侧视觉在往“小骨干 + 按提示分割”走：先把要看的部分抠出来再判断，比整张图分类更稳，也更省电。",
          "On-device vision is moving to a small backbone plus promptable segmentation: cut out the part that matters, "
          "then judge it. Steadier than classifying the whole photo, and lighter on the battery."),
        t("## 实验室覆盖", "## Labs"),
        "\n".join([t("- **Google**：MobileNetV4（见上）", "- **Google**: MobileNetV4 (see above)"),
                   t("- **Meta**：SAM 2（见上）", "- **Meta**: SAM 2 (see above)"),
                   t("- **Apple**：今天没有新发布", "- **Apple**: no new release today")]),
    ])


def cards_of(c: Clock, t: Lang) -> list[dict]:
    """Paper titles and links are real public arXiv papers, and the brief and the lab alert cite real public papers and
    repositories; every summary is our own words, and none of it is news of the demo day. Mail and the session report
    are made up and carry no link."""
    return [
        {"at": c.at(-1, "07:02"), "origin": "arxiv", "kind": "paper", "project_id": "p-loaflog",
         "title": "MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications",
         "link": "https://arxiv.org/abs/1704.04861", "dedupe_key": "1704.04861", "body": None,
         "summary": paper(t, t("为手机设计的轻量卷积网络：用深度可分离卷积大幅减少计算量，精度只掉一点。",
                               "Lightweight convolutional networks for phones: depthwise separable convolutions cut the "
                               "compute a lot for a small loss in accuracy."),
                          t("Loaflog 想在手机上本地给面包切面打分，这是最常用的起点。",
                            "Loaflog wants to score crumb photos on the phone itself; this is the usual starting point."),
                          "Loaflog")},
        {"at": c.at(0, "07:02"), "origin": "arxiv", "kind": "paper", "project_id": "p-loaflog",
         "title": "EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks",
         "link": "https://arxiv.org/abs/1905.11946", "dedupe_key": "1905.11946", "body": None,
         "summary": paper(t, t("按比例同时放大网络的深度、宽度和输入分辨率，用更少的参数得到更高的精度。",
                               "Scales network depth, width and input resolution together, getting better accuracy with "
                               "fewer parameters."),
                          t("如果 MobileNet 的精度不够，这是下一个要试的模型族。",
                            "If MobileNet is not accurate enough, this is the next family to try."), "Loaflog")},
        {"at": c.at(0, "07:04"), "origin": "hf-daily", "kind": "paper", "project_id": None,
         "title": "Segment Anything", "link": "https://arxiv.org/abs/2304.02643", "dedupe_key": "2304.02643", "body": None,
         "summary": paper(t, t("一个按提示分割图片里任意物体的通用模型，同时公开了大规模分割数据集。",
                               "A general model that segments any object in an image from a prompt, released with a "
                               "large segmentation dataset."),
                          t("可以先把面包切面从背景里抠出来，再打分。",
                            "It could cut the loaf's cross-section out of the background before scoring."), None)},
        {"at": c.at(0, "07:00"), "origin": "brief", "kind": "brief", "project_id": None,
         "title": t(f"今日 AI 简报 · {c.day.month}/{c.day.day}", f"Daily AI brief · {c.day.month}/{c.day.day}"),
         "link": None, "dedupe_key": f"brief-{c.ymd(0)}", "body": brief_body(t),
         "summary": t("MobileNetV4：手机上的新通用骨干网络\nSAM 2 把按提示分割带到视频，挑切面用得上\n实验室：3 家里 2 家有动静",
                      "MobileNetV4: a new general backbone for phones\nSAM 2 brings promptable segmentation to video, "
                      "handy for picking crumb shots\nLabs: 2 of 3 had news")},
        {"at": c.at(0, "07:31"), "origin": "gmail", "kind": "mail", "project_id": None, "body": None,
         "title": t("今日邮件：3 封值得看", "Today's mail: 3 worth reading"), "link": None, "dedupe_key": c.ymd(0),
         "summary": t("内测用户 Casey · 旧手机上传照片闪退 —— 附了崩溃日志，和「修复上传照片闪退」有关\n"
                      "Riley · 图标第二版 —— 三个方向选一个，今天 16:00 过图标时要定\n"
                      "音乐教室 · 上课时间调整 —— 以后改到 18:30（你下一节吉他课在后天）",
                      "Casey (beta tester) · Photo upload crashes on an older phone — crash log attached; related to "
                      "“Fix the photo-upload crash”\n"
                      "Riley · Icon options, round two — pick one of three directions at today's 16:00 icon review\n"
                      "Music school · Lesson time change — from now on 18:30 (your next guitar lesson is the day "
                      "after tomorrow)")},
        {"at": c.at(0, "08:05"), "origin": "watch:Apple", "kind": "alert", "project_id": None,
         "title": t("【确认】Apple 公开 FastVLM：手机上也能跑的视觉语言模型",
                    "[Confirmed] Apple publishes FastVLM, a vision-language model that runs on phones"),
         "link": "https://arxiv.org/abs/2412.13303", "dedupe_key": t("Apple:FastVLM 公开:confirmed", "Apple:FastVLM release:confirmed"),
         "summary": t("官方论文和代码都已公开（Apple 研究团队）\n新的视觉编码器让高分辨率图片的响应快很多\n可以试试给切面照片自动写一句描述",
                      "Official paper and code are public (Apple research)\nA new vision encoder answers much faster on "
                      "high-resolution images\nWorth trying: one-line captions for crumb photos"),
         "body": "\n\n".join([
             t("Apple 研究团队公开了 FastVLM 的论文和代码。它用新的混合视觉编码器 FastViTHD，高分辨率图片产生的视觉 token "
               "更少，第一个字出来得快很多，适合在手机上本地跑。对 Loaflog 来说，可以让它给切面照片写一句描述，和打分放在一起。",
               "Apple's research team published the FastVLM paper and code. Its hybrid vision encoder, FastViTHD, turns "
               "high-resolution images into fewer visual tokens, so the first word comes much sooner, which suits running "
               "on a phone. For Loaflog, it could write a one-line caption for each crumb photo next to the score."),
             t("## 相关链接", "## Links"),
             t("- [arXiv：FastVLM: Efficient Vision Encoding for Vision…](https://arxiv.org/abs/2412.13303)\n"
               "- [github.com：ml-fastvlm](https://github.com/apple-aiml-research/ml-fastvlm)",
               "- [arXiv: FastVLM: Efficient Vision Encoding for Vision…](https://arxiv.org/abs/2412.13303)\n"
               "- [github.com: ml-fastvlm](https://github.com/apple-aiml-research/ml-fastvlm)")])},
        {"at": c.at(0, "08:10"), "origin": "session:crash-fix", "kind": "report", "project_id": "p-loaflog",
         "title": t("闪退复现：5 个用例修好 3 个", "Crash repro: 3 of 5 cases fixed"), "link": None,
         "dedupe_key": "crash-fix-1", "body": None,
         "summary": t("旧手机上一次选 10 张以上照片的 5 个复现用例，修好了 3 个：改成边选边压缩缩略图。"
                      "剩下 2 个和相册权限弹窗有关，明天接着看。",
                      "Of the 5 repro cases (10+ photos on older phones), 3 are fixed by compressing thumbnails while "
                      "picking. The other 2 involve the photo-permission prompt; continuing tomorrow.")},
    ]


def feedback_history(c: Clock, t: Lang, app: str) -> list[dict]:
    """Three loops the way they really run: two ship on their own, one waits for your approval."""
    return [
        {"body": t("推送每条都弹两次", "Every notification shows up twice"), "screen": "today", "at": c.at(-3, "21:12"),
         "steps": [("triaged", "auto", t("同一条推送登记了两次设备，改成每次启动只登记一次；只改 app，走空中更新。",
                                         "The device was registered twice per launch; now once. App-only change, "
                                         "shipped as an over-the-air update."), c.at(-3, "21:15")),
                   ("shipped", "auto", t(f"同一条消息现在只弹一次。划掉 {app} 再打开两次生效。",
                                         f"Each message now shows once. Swipe {app} away and reopen it twice to get "
                                         "the update."), c.at(-3, "21:44"))]},
        {"body": t("Mac 版太素了，侧栏想要毛玻璃那种", "The Mac app looks plain; I'd like a frosted-glass sidebar"),
         "screen": "today", "at": c.at(-2, "22:03"),
         "steps": [("triaged", "auto", t("改 Mac 窗口外观和今天页布局，不动接口。",
                                         "Changes the Mac window look and the Today layout; no API change."),
                    c.at(-2, "22:06")),
                   ("shipped", "auto", t("Mac 版已更新：侧栏改成毛玻璃，今天页分成两栏。点通知里的「重启」生效。",
                                         "Mac app updated: frosted sidebar, two-column Today. Tap “Restart” in the "
                                         "notification."), c.at(-1, "00:12"))]},
        {"body": t("大 widget 里空着的块就别显示了", "Hide empty blocks on the big widget"), "screen": "widget_today",
         "at": c.at(-1, "20:31"),
         "steps": [("triaged", "ask", t("要改桌面小组件（原生部分），需要重装安装包。",
                                        "Touches the home-screen widget (native code); needs a new install."),
                    c.at(-1, "20:36")),
                   ("awaiting_approval", "ask", t("要改桌面小组件（原生部分），需要重装安装包。同意后我来做，装好新包就生效。",
                                                  "Touches the home-screen widget (native code), so it needs a new "
                                                  "install. Approve and I'll build it; it takes effect once you install "
                                                  "the new package."), c.at(-1, "20:40")),
                   ("approve", None, None, c.at(-1, "20:52")),
                   ("shipped", "ask", t("新安装包已发：没有内容的块整块不显示。点通知下载安装后生效。",
                                        "The new package is out: empty blocks are hidden. Tap the notification to "
                                        "download and install it."), c.at(-1, "21:26"))]},
    ]


def extras_of(c: Clock, t: Lang, app: str) -> dict:
    slug = slug_of(app)
    loaflog_commits = (("onboarding: merge the five screens into three", c.iso(-1, "20:30")),
                       ("photos: compress thumbnails while picking", c.iso(-1, "16:10")),
                       ("add overnight crash soak test", c.iso(-2, "17:40")))
    return {
        "taste": [(t("偏好附带代码或演示的论文", "Prefer papers that come with code or a demo"), c.at(-9, "22:00")),
                  (t("手机端的小模型优先；纯大模型评测不感兴趣", "On-device models first; not interested in pure LLM benchmarks"),
                   c.at(-6, "21:50"))],
        "subscription_results": [("brief", t("简报写好：论文 1 篇、新闻 1 条", "Brief written: 1 paper, 1 news item"),
                                  c.at(0, "07:00")),
                                 ("watch", t("新动态 1 条：【确认】Apple 公开 FastVLM：手机上也能跑的视觉语言模型",
                                             "1 lab update: [Confirmed] Apple publishes FastVLM, a vision-language model "
                                             "that runs on phones"), c.at(0, "08:05")),
                                 ("mail", t("今日邮件：3 封值得看", "Today's mail: 3 worth reading"), c.at(0, "07:31"))],
        # Sam's lab watch list (the hub starts every instance with its own default list)
        "watch_config": {"labs": ["Google", "Meta", "Apple"], "every_hours": 8},
        "review": {"summary": t("4 件完成 3 件：注册流程、第一首歌、鞋柜都按时完成；定价没动。",
                                "3 of 4 done: the sign-up flow, song one and the shoe rack on time; pricing didn't move."),
                   "completed_item_ids": ["i-prev-signup", "i-prev-song1", "i-prev-shoes"],
                   "missed_item_ids": ["i-lf-pricing"],
                   "patterns": [t("Loaflog 的活都挤在周末，工作日晚上只推进了吉他和整理",
                                  "Loaflog work piled up on weekends; weekday evenings only moved guitar and the closet"),
                                t("有固定时间的事（吉他课、送捐赠）都做完了，没定时间的事容易拖",
                                  "Things with a fixed time (lessons, drop-offs) got done; things without one slipped")],
                   "user_note": t("下一期把定价放第一周，工作日上午做 Loaflog。",
                                  "Next period: pricing in week one, Loaflog on weekday mornings."),
                   "at": c.at(-5, "21:10")},
        "summaries": {
            "p-loaflog": t("新引导只差录视频；上传照片闪退修好 3/5，夜间测试在跑。",
                           "The new onboarding only needs its video; photo-upload crash 3/5 fixed, overnight test running."),
            "p-app": t("最近 3 条反馈都已修好上线；今天页还想再精简。",
                       "The last 3 feedback items all shipped; the Today page could be leaner."),
            "p-guitar": t("这周练了 4 次；第二首的副歌能弹下来了，琴弦该换了。",
                          "4 sessions this week; song two's chorus works, and the strings need replacing."),
            "p-closet": t("夏装清出一袋，还差一袋；周末前送去捐赠点。",
                          "One bag of summer clothes is out, one to go; drop-off before the weekend."),
        },
        "summary_evidence": {"p-loaflog": sha7(loaflog_commits[0][0]), "p-app": "inferred", "p-guitar": "inferred",
                             "p-closet": "inferred"},
        "summary_at": c.at(-1, "23:00"),
        # project cards (api.md 项目概况), one per source: Loaflog's own session keeps ~/code/loaflog/overview.json,
        # Claude wrote the app's on refresh, Sam set the guitar one in chat; the closet project has none yet
        "overviews": {
            "p-loaflog": overview_of(
                "project", c.iso(-1, "22:45"),
                one_liner=t("烘焙记录 app：拍下每次发面和出炉，记住哪种配方最稳",
                            "A sourdough bake log: snap every rise and bake, and remember which recipe works"),
                status=t("新引导只差录走查视频；上传照片闪退的夜间测试跑到 31/40 轮。下一步：**定价**。",
                         "The new onboarding only needs its walkthrough video; the photo-upload crash soak is at "
                         "31/40 runs. Next: **pricing**."),
                kill={"state": "running",
                      "setting": t("40 位内测用户用满两周；第二周还在记录的不到 30%，就先不上 1.0，回头改记录流程",
                                   "40 beta testers for two weeks; if under 30% still log in week two, hold 1.0 and "
                                   "rework the logging flow"),
                      "progress": t("第 9 天：40 人里 31 人这周还在记（78%）", "Day 9: 31 of 40 still logging this week (78%)")},
                score=3.5,
                abstract=t("把每次烘焙的发面时间、温度和照片记在一处，自动比出哪种配方最稳；离线能用，不注册也能记。",
                           "Rise times, temperatures and photos of every bake in one place, with a comparison of "
                           "which recipe holds up; works offline, no account needed."),
                novelty=t("同类 app 多是食谱合集，只记结果不记过程，见[竞品对比](https://example.com/loaflog-competitors)。",
                          "Similar apps are recipe collections that keep results, not the process; see the "
                          "[competitor notes](https://example.com/loaflog-competitors)."),
                significance=t("内测里最常听到的是“终于知道上次为什么塌了”。下一步：定价，然后公开 1.0。",
                               "The beta's most common comment: “now I know why the last one collapsed.” Next: "
                               "pricing, then a public 1.0."),
                objections=[t("记录太麻烦，新手坚持不了两周？——能回答：第 9 天还有 78% 在记，引导砍到 3 屏后会更好。",
                              "Too much logging for beginners to last two weeks? Answered: 78% still log on day 9, "
                              "and onboarding drops to three screens."),
                            t("和用笔记 app 记有什么区别？——部分回答：自动比配方是笔记做不到的，但还没有数据。",
                              "Why not just a notes app? Partly answered: notes can't compare recipes, but there is "
                              "no data on it yet.")],
                decision=t("继续；内测满两周再定要不要上 1.0。", "Keep going; decide on 1.0 after the two-week beta."),
                status_file="~/code/loaflog/STATUS.md", status_changed=True, evidence="~/code/loaflog/overview.json"),
            "p-app": overview_of(
                "claude", c.iso(-1, "23:00"),
                one_liner=t(f"{app}：会话进展、笔记和两周计划都在手机上看得到",
                            f"{app}: session progress, notes and the two-week plan, all on the phone"),
                status=t("最近 3 条反馈都已修好上线；今天页还想再精简。",
                         "The last 3 feedback items all shipped; the Today page could be leaner."),
                kill=None, score=None, abstract=None, novelty=None, significance=None, objections=None, decision=None,
                status_file=None, status_changed=False, evidence="inferred"),
            "p-guitar": overview_of(
                "me", c.iso(-3, "21:30"),
                one_liner=t("在开放麦上弹完三首歌", "Play three songs at the open mic"),
                status=t("第二首的副歌能弹下来了；第三首还没选。", "Song two's chorus works; song three isn't picked yet."),
                kill={"state": "not_started",
                      "setting": t("开放麦前一周给朋友完整弹一遍三首；卡壳超过两次就换一首简单的",
                                   "A week before the open mic, play all three for friends; more than two stalls and "
                                   "an easier song goes in"),
                      "progress": ""},
                score=None, abstract=None, novelty=None, significance=None, objections=None, decision=None,
                status_file=None, status_changed=False, evidence=None),
        },
        "snapshots": {
            "p-app": {"taken_at": c.iso(-1, "23:00"), "worktrees": [
                {"name": "main", "branch": "main", "path": f"~/code/{slug}", "status": "in-review",
                 "last_output": t("维护会话：3 条反馈都已上线，等新反馈", "Maintainer: 3 feedback items shipped, waiting for new ones"),
                 "last_activity_at": c.iso(-1, "21:30")},
                {"name": "mobile", "branch": "sam/mobile", "path": f"~/code/{slug}-worktrees/mobile", "status": "in-review",
                 "last_output": t("已合并：大 widget 空块不显示", "Merged: big widget hides empty blocks"),
                 "last_activity_at": c.iso(-1, "21:20")},
                {"name": "desktop", "branch": "sam/desktop", "path": f"~/code/{slug}-worktrees/desktop", "status": "in-review",
                 "last_output": t("已合并：侧栏毛玻璃", "Merged: frosted sidebar"), "last_activity_at": c.iso(-1, "00:05")}],
             "commits": [{"repo": slug, "sha": sha7(s), "subject": s, "at": a} for s, a in (
                 ("mobile: big widget hides empty blocks", c.iso(-1, "21:18")),
                 ("desktop: frosted sidebar, two-column today", c.iso(-1, "00:02")),
                 ("mobile: register the push device once per launch", c.iso(-3, "21:38")))]},
            "p-loaflog": {"taken_at": c.iso(-1, "23:00"), "worktrees": [
                {"name": "crash-fix", "branch": "fix/photo-crash", "path": "~/code/loaflog", "status": "in-progress",
                 "last_output": "overnight soak 31/40 · crash rate 0.4%", "last_activity_at": c.iso(-1, "22:40")}],
             "commits": [{"repo": "loaflog", "sha": sha7(s), "subject": s, "at": a} for s, a in loaflog_commits]},
        },
        # app opens per day, D-6 .. D (the system page's 7-day metric)
        "opens": {-6: ["07:41", "12:30", "18:05", "21:47"], -5: ["07:35", "08:10", "12:02", "17:40", "21:20", "21:58"],
                  -4: ["07:50", "13:15", "22:05"], -3: ["07:33", "13:20", "18:30", "21:05", "22:40"],
                  -2: ["07:31", "09:12", "12:44", "16:30", "20:40", "21:41", "22:10"], -1: ["07:31", "12:15", "15:02", "20:31", "21:52"],
                  0: ["07:32", "12:40"]},
    }


def overview_of(source: str, checked_at: str, *, one_liner: str, status: str, kill: dict | None, score: float | None,
                abstract: str | None, novelty: str | None, significance: str | None, objections: list[str] | None,
                decision: str | None, status_file: str | None, status_changed: bool, evidence: str | None) -> dict:
    """A whole project overview as the hub stores it (PUT /projects/{id}/overview); Sam's projects have no paper."""
    return {"source": source, "one_liner": one_liner, "status": status, "kill": kill, "paper": None,
            "abstract": abstract, "novelty": novelty, "significance": significance, "objections": objections,
            "score": score, "decision": decision, "checked_at": checked_at, "status_file": status_file,
            "status_changed": status_changed, "evidence": evidence}


def ask_feedback(t: Lang) -> dict:
    return {"body": t("晚间提问能不能在小组件上直接回", "Can I answer the evening question right from the widget?"),
            "triaged": t("要给桌面小组件加输入框，属于原生改动。", "Adds an input box to the home-screen widget: a native change."),
            "awaiting": t("要给桌面小组件加输入框，属于原生改动，需要重装安装包；晚间提问的时间和内容不变。同意后我来做。",
                          "Adds an input box to the home-screen widget. That is a native change and needs a new "
                          "install; the evening question itself stays the same. Approve and I'll build it.")}


# ---------------------------------------------------------------- mock server data (mobile/mock)

def mock_extra_of(c: Clock, t: Lang, app: str, seed: dict) -> dict:
    """Everything the mock server shows beyond the seed: one of each state the app can render."""
    x = extras_of(c, t, app)
    cur = next(p for p in seed["plans"] if p["status"] == "active")
    prev = next(p for p in seed["plans"] if p["status"] == "closed")
    note_id, amp_item = "r-demo-amp", "note-r-demo-amp"
    amp = t("找一个二手练习音箱", "Find a used practice amp")

    def rec(id_, n, hm, author, source, kind, tier, item_id, title, body, evidence, **more):
        return {"id": id_, "at": c.iso(n, hm), "author": author, "source": source, "kind": kind, "tier": tier,
                "item_id": item_id, "title": title, "body": body, "evidence": evidence, "needs_processing": False, **more}

    records = [
        {**rec(note_id, -1, "23:40", "me", "app", "note", "log", None, amp,
               t("预算 150 以内，要带耳机口", "Under 150, with a headphone jack"), None), "needs_processing": True},
        rec("r-demo-cal", -1, "23:45", "system", AGENT, "log", "digest", "i-lf-beta-date",
            t("已建日程：和 Jordan 喝咖啡 明天 10:00", "Event added: Coffee with Jordan tomorrow 10:00"),
            "", None, undo={"type": "calendar", "op": "create", "event_id": "demo-coffee", "before": None}, undone_at=None),
        rec("r-demo-amp-item", -1, "23:50", "system", "worker", "log", "digest", amp_item,
            t("从笔记整理出新事项：找二手音箱", "New item from a note: find a used amp"),
            t("worker 把一条「请处理」的笔记整理成了事项，等你确认。", "The worker turned a “please handle” note into an item; "
              "it waits for your OK."), "inferred"),
        rec("r-demo-raw", -1, "23:55", "system", "worker", "log", "log", amp_item,
            t("找二手音箱：status waiting_you → active", "Find a used amp: status waiting_you → active"),
            t(f"来源笔记 {note_id}，owner auto_then_me（示例：内部值应显示成可读的文字）",
              f"Source note {note_id}, owner auto_then_me (demo: raw values should render as readable text)"),
            f"record:{note_id}"),
        rec("r-demo-price", 0, "03:50", "system", "worker", "alert", "interrupt", None,
            t("收藏的二手音箱降到 $140 了", "A saved amp listing dropped to $140"),
            t("你收藏的那台二手练习音箱现在 $140，低于你定的 $150 上限。",
              "The used practice amp on your saved list is now $140, under your $150 limit."),
            None),
        rec("r-demo-brief", 0, "07:30", "system", AGENT, "chat", "quiet", None, t("早上简报", "Morning brief"),
            t("早上好。今天重点：新手引导、练琴 20 分钟。1 件事等你拍板，12:30 和 Jordan 吃午饭。",
              "Good morning. Focus: onboarding and 20 minutes of guitar. One thing needs your call; lunch with "
              "Jordan at 12:30."), None),
        rec("r-demo-md", 0, "07:40", "system", AGENT, "chat", "digest", None, t("今天建议这样排", "A plan for today"),
            t("今天建议这样排：\n\n1. **上午**：录新手引导的走查视频\n2. **下午**：14:00 改完引导，16:00 和 Riley 过图标\n\n"
              "还有两件小事：\n- 回 Casey 的崩溃日志邮件\n- 看一眼 [内测清单](https://example.com/beta-checklist)",
              "A plan for today:\n\n1. **Morning**: record the onboarding walkthrough\n2. **Afternoon**: finish "
              "onboarding at 14:00, icon review with Riley at 16:00\n\nTwo small things:\n- Reply to Casey's crash-log "
              "email\n- Skim the [beta checklist](https://example.com/beta-checklist)"), None, feedback_id=None),
        rec("r-demo-route", 0, "07:41", "system", AGENT, "chat", "log", None,
            t("已转给 Mac，醒来后回你", "Handed to the Mac; it will reply when it wakes"),
            t("已转给 Mac，醒来后回你", "Handed to the Mac; it will reply when it wakes"), None, feedback_id=None),
        rec("r-demo-maint", -1, "19:35", "system", "maintainer", "chat", "digest", None,
            t("三行够吗？还是想要两行 + 点开看全文？", "Is three lines right, or two lines plus tap for more?"),
            t("三行够吗？还是想要两行 + 点开看全文？", "Is three lines right, or two lines plus tap for more?"), None,
            feedback_id="f-demo-1"),
    ]
    revision_at = c.at(0, "07:00")
    plans = [
        {"id": f"p-{c.ymd(10)}", "start": c.ymd(10), "end": c.ymd(23), "goal_ids": cur["goal_ids"],
         "item_ids": ["i-lf-pricing", "i-gt-song3", "i-cl-donate"], "status": "draft",
         "created_at": c.iso(-1, "23:50"), "closed_at": None},
        {"id": f"{cur['id']}-r{revision_at:%Y%m%d%H%M}", "start": cur["start"], "end": cur["end"],
         "goal_ids": cur["goal_ids"], "item_ids": cur["item_ids"] + [amp_item], "status": "draft",
         "created_at": revision_at.isoformat(timespec="seconds"), "closed_at": None, "revises": cur["id"]},
    ]
    r = x["review"]
    card_extra = {"1704.04861": ("worker", "saved", None), "1905.11946": ("worker", "new", None),
                  "2304.02643": ("worker", "new", None), c.ymd(0): ("worker", "new", None),
                  f"brief-{c.ymd(0)}": ("worker", "new", None),
                  t("Apple:FastVLM 公开:confirmed", "Apple:FastVLM release:confirmed"): ("worker", "new", None),
                  "crash-fix-1": ("cards", "new", "a-mock-cover")}  # a-mock-cover: the mock serves an image for it
    cards = []
    for i, card in enumerate(cards_of(c, t), 1):
        source, status, image = card_extra[card["dedupe_key"]]
        cards.append({"id": f"c-demo-{i}", "at": card["at"].isoformat(timespec="seconds"), "source": source,
                      **{k: card[k] for k in ("origin", "kind", "project_id", "title", "summary", "body", "link",
                                              "dedupe_key")},
                      "status": status, "item_id": None, "image_attachment_id": image})
    # the record the hub writes (and pushes) when an alert card arrives (api.md 信息流改成报告)
    alert = next(card for card in cards if card["kind"] == "alert")
    records.append(rec("r-demo-news", 0, "08:05", "system", "hub", "log", "digest", None,
                       t(f"新动态：{alert['title']}", f"News: {alert['title']}"), alert["summary"], alert["link"],
                       card_id=alert["id"], category="news"))
    records.sort(key=lambda r: r["at"])  # the mock lists records in file order, oldest first
    return {
        "demo_day": c.ymd(0),
        "sources": [
            {"name": "worker", "expected_interval_s": 300, "last_seen_at": None},
            {"name": "nas-backup", "expected_interval_s": 900, "last_seen_at": c.iso(0, "03:00")},
            {"name": AGENT, "expected_interval_s": 300, "last_seen_at": None},
            {"name": "google-calendar", "expected_interval_s": 3600, "last_seen_at": None},
            {"name": "maintainer", "expected_interval_s": 900, "last_seen_at": None},
            {"name": "feed-papers", "expected_interval_s": 86400, "last_seen_at": c.iso(0, "07:00"), "health": "ok",
             "health_detail": None, "health_at": c.iso(0, "07:05")},
        ],
        "records": records,
        "plans": plans,
        "items": [{"id": amp_item, "title": amp, "category": "life", "status": "waiting_you",
                   "next_step": t("问问卖家那台 $140 的练习音箱", "Message the seller about the $140 practice amp"),
                   "next_at": c.iso(0, "09:00"), "owner": "auto_then_me",
                   "done_definition": t("你买到音箱并试过一次", "You buy an amp and try it once"), "goal_id": "g-openmic",
                   "progress": {"value": 3, "target": 10, "unit": t("个候选", "candidates")},
                   "updated_at": c.iso(-1, "23:50"), "updated_by": "worker", "project_id": "p-guitar"}],
        "reviews": [{"plan_id": prev["id"], "created_at": r["at"].isoformat(timespec="seconds"),
                     **{k: r[k] for k in ("summary", "completed_item_ids", "missed_item_ids", "patterns", "user_note")},
                     "status": "done"}],
        "drafts": [{"id": "d-demo-lesson", "at": c.iso(-1, "23:40"), "source": "worker", "channel": "email",
                    "to": t("音乐教室前台", "Music school front desk"),
                    "subject": t("确认新的上课时间", "Confirming the new lesson time"),
                    "body": t("你好，\n\n收到以后上课改到 18:30 的通知，这个时间可以。麻烦还是用原来的教室。\n\n谢谢！\nSam",
                              "Hi,\n\nThanks for letting me know lessons move to 18:30; that works for me. "
                              "Could we keep the same room?\n\nThanks,\nSam"),
                    "item_id": "i-gt-practice", "status": "pending"}],
        "projects": [{"id": "p-loaflog-export", "title": "loaflog-export", "area": "research", "status": "proposed",
                      "repo_path": "~/code/loaflog-export", "goal_id": None, "summary": None, "summary_evidence": None,
                      "summary_at": None}],
        "snapshots": x["snapshots"],
        "auth": [{"name": "google-calendar-write", "ok": True, "detail": None, "checked_at": c.iso(0, "05:00")},
                 {"name": "gmail-read", "ok": True, "detail": None, "checked_at": c.iso(0, "05:00")},
                 {"name": "claude-server", "ok": True, "detail": None, "checked_at": c.iso(0, "05:30")},
                 {"name": "claude-mac", "ok": True, "detail": None, "checked_at": c.iso(0, "04:00")}],
        "project_summaries": {pid: {"summary": s, "summary_evidence": x["summary_evidence"][pid],
                                    "summary_at": x["summary_at"].isoformat(timespec="seconds")}
                              for pid, s in x["summaries"].items()},
        "project_overviews": x["overviews"],
        "cards": cards,
        "feedback": [{"id": "f-demo-1", "at": c.iso(-1, "19:30"),
                      "body": t("信息流卡片太长了，能不能默认只显示三行？", "Feed cards are too long. Can they show three lines by default?"),
                      "attachments": [],
                      "context": {"screen": "feed", "item_id": None, "project_id": None,
                                  "app_update_id": "00000000-0000-4000-8000-000000000001"},
                      "status": "awaiting_approval", "ship_mode": "ask",
                      "summary": t("把卡片摘要默认截到 3 行，点开卡片看全文。已改好，同意后发空中更新，冷启动两次生效。",
                                   "Card summaries stop at three lines; open a card for the full text. Ready: approve "
                                   "and it ships as an over-the-air update (two cold starts to take effect)."),
                      "updated_at": c.iso(-1, "19:40")}],
        "feedback_messages": [{"id": "fm-demo-1", "feedback_id": "f-demo-1", "at": c.iso(-1, "19:35"),
                               "author": "maintainer",
                               "body": t("三行够吗？还是想要两行 + 点开看全文？", "Is three lines right, or two lines plus tap for more?"),
                               "attachments": []}],
        "taste": [{"id": f"t-demo-{i}", "at": at.isoformat(timespec="seconds"), "text": text, "source": AGENT}
                  for i, (text, at) in enumerate(x["taste"], 1)],
        "subscriptions": [
            {"id": sub_id, "name": name, "kind": sub_id, "at": at, "enabled": True, "config": config,
             "last_run_at": ran.isoformat(timespec="seconds"), "last_result": result, "health": "ok"}
            for (sub_id, result, ran), name, at, config in zip(
                x["subscription_results"],
                (t("每日简报", "Daily brief"), t("实验室动态", "Lab watch"), t("每日邮件", "Daily mail")),
                ("07:00", "08:00", "07:30"), ({}, x["watch_config"], {}), strict=True)],
        "events": [{"uid": e["uid"], "start": e["start"].isoformat(timespec="seconds"),
                    "end": e["end"].isoformat(timespec="seconds"), "all_day": e["all_day"], "title": e["title"],
                    "location": e["location"], "read_only": False} for e in calendar_of(c, t)],
        # what the mock writes when it pretends to draft a review (POST /jobs draft_review)
        "simulated_review": {"summary": t("（假服务器起草）这期 Loaflog 推进稳定，换琴弦一直没动。",
                                          "(mock draft) Loaflog moved steadily this period; the restring never happened."),
                             "patterns": [t("「换琴弦」没定时间，两期都没动", "“Restring” has no time set and slipped twice")]},
    }


# ---------------------------------------------------------------- files

def write_private(path: Path, text: str) -> None:
    path.write_text(text)
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")


def meta(out: Path) -> dict:
    return json.loads((out / "demo.json").read_text())


def story(a) -> tuple[Clock, Lang]:
    tz = ZoneInfo(a.timezone)
    day = datetime.now(tz).date() if a.day == "today" else date.fromisoformat(a.day)
    return Clock(day, tz), Lang(a.language)


def cmd_seed(a) -> None:
    c, t = story(a)
    write_json(Path(a.out), seed_of(c, t, a.app_name, a.morning_at, a.evening_at))
    print(f"seed for {c.day} ({a.timezone}, {a.language}) written to {a.out}")


def cmd_mock(a) -> None:
    c, t = story(a)
    seed = seed_of(c, t, a.app_name, a.morning_at, a.evening_at)
    write_json(Path(a.seed_out), seed)
    write_json(Path(a.extra_out), mock_extra_of(c, t, a.app_name, seed))
    print(f"mock data for {c.day} ({a.timezone}, {a.language}) written to {a.seed_out} and {a.extra_out}")


def openssl(*args: str) -> None:
    subprocess.run(["openssl", *args], check=True, capture_output=True)


def fcm_placeholder(out: Path) -> Path:
    """A service-account file the hub can load without a Firebase project: Android push stays off (the web app
    does not need it). Replace it with a real one to push to the Android app."""
    key = out / "fcm-placeholder.key"
    openssl("genpkey", "-algorithm", "RSA", "-pkeyopt", "rsa_keygen_bits:2048", "-out", str(key))
    path = out / "fcm-placeholder.json"
    write_private(path, json.dumps({"type": "service_account", "project_id": "demo-no-push", "private_key_id": "demo",
                                    "private_key": key.read_text(), "client_email": "demo-no-push",
                                    "token_uri": "https://oauth2.googleapis.com/token"}, indent=2))
    key.unlink()
    return path


def cmd_build(a) -> None:
    out = Path(a.out).resolve()
    out.mkdir(parents=True)
    c, t = story(a)
    fcm = fcm_placeholder(out) if a.fcm_credentials == "placeholder" else Path(a.fcm_credentials).resolve()
    if not fcm.is_file():
        raise SystemExit(f"--fcm-credentials {fcm} is not a file")
    write_json(out / "seed.json", seed_of(c, t, a.app_name, a.morning_at, a.evening_at))
    (out / "calendar.ics").write_text(ics_of(c, t))
    (out / "attachments").mkdir(mode=0o700)
    (out / "web").mkdir()  # MOJITO_WEB_DIR: put a web build here to serve it at /app
    (out / "ical-extra-urls").write_text("")  # MOJITO_ICAL_EXTRA_FILE: no subscribed calendars
    openssl("ecparam", "-name", "prime256v1", "-genkey", "-noout", "-out", str(out / "vapid.pem"))
    (out / "vapid.pem").chmod(stat.S_IRUSR | stat.S_IWUSR)
    tokens = {role: secrets.token_urlsafe(32) for role in ROLES}
    write_private(out / "tokens.json", json.dumps({tok: role for role, tok in tokens.items()}, indent=2))
    hub = f"http://127.0.0.1:{a.port}"
    write_private(out / "hub.env", "\n".join([
        f"MOJITO_DB={out / 'demo.db'}", f"MOJITO_TOKENS={out / 'tokens.json'}", f"MOJITO_SEED={out / 'seed.json'}",
        f"MOJITO_ICAL_URL=file://{out / 'calendar.ics'}",
        f"MOJITO_ICAL_EXTRA_FILE={out / 'ical-extra-urls'}", f"MOJITO_FCM_CREDENTIALS={fcm}",
        f"MOJITO_ATTACHMENTS_DIR={out / 'attachments'}", f"MOJITO_VAPID_KEY_FILE={out / 'vapid.pem'}",
        f"MOJITO_VAPID_SUBJECT={a.public_url}", f"MOJITO_PUBLIC_URL={a.public_url}", f"MOJITO_WEB_DIR={out / 'web'}",
        f"MOJITO_TIMEZONE={a.timezone}", f"MOJITO_OWNER_NAME={OWNER_NAME}", f"MOJITO_CONTACT_EMAIL={CONTACT_EMAIL}"]) + "\n")
    clients = out / "clients"
    clients.mkdir(mode=0o700)
    for name, var, role, extra in (("worker.env", "MOJITO_WORKER_TOKEN", "worker", [f"MOJITO_TIMEZONE={a.timezone}"]),
                                   ("agent.env", "MOJITO_AGENT_TOKEN", "agent", [f"MOJITO_TIMEZONE={a.timezone}"]),
                                   ("maintainer.env", "MOJITO_MAINTAINER_TOKEN", "maintainer", []),
                                   ("cards.env", "MOJITO_CARDS_TOKEN", "source:cards", [])):
        write_private(clients / name, "\n".join([f"MOJITO_HUB_URL={hub}", f"{var}={tokens[role]}", *extra]) + "\n")
    write_private(clients / "app-token.txt", tokens["app"] + "\n")
    write_json(out / "demo.json", {"day": c.ymd(0), "timezone": a.timezone, "language": a.language,
                                   "app_name": a.app_name, "port": a.port, "hub": hub})
    print(f"built {out}\n  start the hub with hub.env, then run: load, (stop the hub) backdate, (start it again)\n"
          f"  hub address {hub}   app token: clients/app-token.txt")


# ---------------------------------------------------------------- API

class Hub:
    def __init__(self, out: Path):
        self.url = meta(out)["hub"]
        self.token = {role: tok for tok, role in json.loads((out / "tokens.json").read_text()).items()}

    def call(self, role: str, method: str, path: str, body: dict | None):
        headers = {"Authorization": f"Bearer {self.token[role]}"}
        data = None
        if body is not None:
            headers["Content-Type"] = "application/json"
            data = json.dumps(body).encode()
        req = urllib.request.Request(self.url + path, data=data, method=method, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                text = resp.read().decode()
        except urllib.error.HTTPError as e:  # re-raised with the hub's detail
            raise RuntimeError(f"{method} {path} -> {e.code}: {e.read().decode()}") from e
        return None if text == "" else json.loads(text)


class NewRecords:
    """Records the hub writes while `load` talks to it, each tagged with its story time (backdate moves them)."""

    def __init__(self, db: sqlite3.Connection):
        self.db, self.tagged = db, []
        self.last = db.execute("SELECT COALESCE(MAX(rowid), 0) FROM records").fetchone()[0]

    def tag(self, at: datetime) -> None:
        rows = self.db.execute("SELECT rowid, id FROM records WHERE rowid > ? ORDER BY rowid", (self.last,)).fetchall()
        self.tagged += [[rid, db_ts(at)] for _, rid in rows]
        if rows:
            self.last = rows[-1][0]


def cmd_load(a) -> None:
    out = Path(a.out).resolve()
    m = meta(out)
    c, t, app = Clock(date.fromisoformat(m["day"]), ZoneInfo(m["timezone"])), Lang(m["language"]), m["app_name"]
    db = sqlite3.connect(f"file:{out / 'demo.db'}?mode=ro", uri=True)
    if db.execute("SELECT COUNT(*) FROM devices").fetchone()[0] != 0:
        raise SystemExit("a device is already registered: loading history now would push to it. Use reset instead.")
    if db.execute("SELECT COUNT(*) FROM cards").fetchone()[0] != 0:
        raise SystemExit("already loaded (cards exist). Use reset, or build a new instance.")
    hub, x, new = Hub(out), extras_of(c, t, app), NewRecords(db)
    done = {"load_start": db_ts(datetime.now(UTC) - timedelta(seconds=1)), "cards": [], "taste": [],
            "subscriptions": [], "feedback": []}

    # Sam set the lab watch list in chat a few days ago (the hub records the change)
    watch = next(s for s in hub.call("app", "GET", "/subscriptions", None)["subscriptions"] if s["id"] == "watch")
    hub.call("worker", "PUT", "/subscriptions/watch", {"at": watch["at"], "config": x["watch_config"]})
    new.tag(c.at(-4, "21:05"))

    for card in cards_of(c, t):
        body = {k: card[k] for k in ("origin", "kind", "project_id", "title", "summary", "body", "link", "dedupe_key")}
        done["cards"].append([hub.call("source:cards", "POST", "/cards", body)["id"], db_ts(card["at"])])
        new.tag(card["at"])

    for text, at in x["taste"]:
        done["taste"].append([hub.call("agent", "POST", "/taste", {"text": text})["id"], db_ts(at)])
        new.tag(at)

    for sub_id, result, at in x["subscription_results"]:
        hub.call("worker", "POST", f"/subscriptions/{sub_id}/result", {"result": result, "health": "ok"})
        done["subscriptions"].append([sub_id, db_ts(at)])
        new.tag(at)

    prev_plan = next(p["id"] for p in json.loads((out / "seed.json").read_text())["plans"] if p["status"] == "closed")
    r = x["review"]
    hub.call("worker", "PUT", f"/reviews/{prev_plan}", {k: r[k] for k in ("summary", "completed_item_ids", "missed_item_ids", "patterns")})
    hub.call("app", "POST", f"/reviews/{prev_plan}/finish", {"user_note": r["user_note"]})
    done["review"] = [prev_plan, db_ts(r["at"])]
    new.tag(r["at"])

    for pid, summary in x["summaries"].items():
        hub.call("worker", "PUT", f"/projects/{pid}/summary", {"summary": summary, "summary_evidence": x["summary_evidence"][pid]})
    done["summary_at"] = db_ts(x["summary_at"])
    for pid, snap in x["snapshots"].items():
        hub.call("worker", "PUT", f"/projects/{pid}/snapshot", snap)
    new.tag(x["summary_at"])

    # project cards: the worker copies overview.json / writes Claude's; Sam's own edit came through chat (agent) and
    # leaves a change record with an undo
    for pid, overview in x["overviews"].items():
        hub.call("agent" if overview["source"] == "me" else "worker", "PUT", f"/projects/{pid}/overview", overview)
        new.tag(datetime.fromisoformat(overview["checked_at"]))

    events = [{"at": c.iso(n, hm), "kind": "view", "name": "app_open", "detail": None} for n, hms in x["opens"].items() for hm in hms]
    hub.call("app", "POST", "/usage", {"events": events})

    for fb in feedback_history(c, t, app):
        context = {"screen": fb["screen"], "item_id": None, "project_id": None, "app_update_id": None}
        fid = hub.call("app", "POST", "/feedback", {"body": fb["body"], "attachment_ids": [], "context": context})["id"]
        new.tag(fb["at"])
        for status, ship_mode, summary, at in fb["steps"]:
            if status == "approve":
                hub.call("app", "POST", f"/feedback/{fid}/decision", {"action": "approve"})
            else:
                hub.call("maintainer", "PUT", f"/feedback/{fid}", {"status": status, "ship_mode": ship_mode, "summary": summary})
            new.tag(at)
        done["feedback"].append([fid, db_ts(fb["at"]), db_ts(fb["steps"][-1][3])])

    done["records"] = new.tagged
    db.close()
    (out / "loaded.json").write_text(json.dumps(done, ensure_ascii=False, indent=2))
    print(f"loaded {len(done['cards'])} cards, {len(done['feedback'])} feedback, {len(done['records'])} records; "
          "stop the hub, then run backdate")


def cmd_backdate(a) -> None:
    out = Path(a.out).resolve()
    done = json.loads((out / "loaded.json").read_text())
    start = done["load_start"]
    db = sqlite3.connect(out / "demo.db")
    with db:
        for cid, at in done["cards"]:
            db.execute("UPDATE cards SET at = ? WHERE id = ?", (at, cid))
        for tid, at in done["taste"]:
            db.execute("UPDATE taste_notes SET at = ? WHERE id = ?", (at, tid))
        for sid, at in done["subscriptions"]:
            db.execute("UPDATE subscriptions SET last_run_at = ? WHERE id = ?", (at, sid))
        db.execute("UPDATE reviews SET created_at = ? WHERE plan_id = ?", (done["review"][1], done["review"][0]))
        db.execute("UPDATE projects SET summary_at = ? WHERE summary_at >= ?", (done["summary_at"], start))
        for fid, at, updated in done["feedback"]:
            db.execute("UPDATE feedback SET at = ?, updated_at = ? WHERE id = ?", (at, updated, fid))
        for rid, at in done["records"]:
            db.execute("UPDATE records SET at = ? WHERE id = ?", (at, rid))
        left = db.execute("SELECT title FROM records WHERE at >= ?", (start,)).fetchall()
        if left:
            raise SystemExit(f"records written during load still carry load time (written by the hub on its own?): {left}")
    db.execute("PRAGMA wal_checkpoint(TRUNCATE)")
    db.close()
    golden = out / "golden"
    if golden.exists():
        shutil.rmtree(golden)
    golden.mkdir()
    shutil.copy2(out / "demo.db", golden / "demo.db")
    shutil.copytree(out / "attachments", golden / "attachments")
    print(f"backdated; golden copy in {golden}")


def cmd_reset(a) -> None:
    out = Path(a.out).resolve()
    for suffix in ("-wal", "-shm"):
        (out / f"demo.db{suffix}").unlink(missing_ok=True)
    shutil.copy2(out / "golden" / "demo.db", out / "demo.db")
    shutil.rmtree(out / "attachments")
    shutil.copytree(out / "golden" / "attachments", out / "attachments")
    (out / "attachments").chmod(0o700)
    print("reset to golden; start the hub and reopen the app")


def cmd_ask(a) -> None:
    out = Path(a.out).resolve()
    hub, fb = Hub(out), ask_feedback(Lang(meta(out)["language"]))
    context = {"screen": "widget_today", "item_id": None, "project_id": None, "app_update_id": None}
    fid = hub.call("app", "POST", "/feedback", {"body": fb["body"], "attachment_ids": [], "context": context})["id"]
    hub.call("maintainer", "PUT", f"/feedback/{fid}", {"status": "triaged", "ship_mode": "ask", "summary": fb["triaged"]})
    hub.call("maintainer", "PUT", f"/feedback/{fid}", {"status": "awaiting_approval", "ship_mode": "ask", "summary": fb["awaiting"]})
    print(f"feedback {fid} is waiting for approval")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    def story_args(s):
        s.add_argument("--day", required=True, help='the story\'s today: YYYY-MM-DD or "today" (in --timezone)')
        s.add_argument("--timezone", required=True, help="IANA zone, the hub's MOJITO_TIMEZONE (e.g. Europe/Berlin)")
        s.add_argument("--language", required=True, choices=("zh", "en"), help="UI language written into the seed")
        s.add_argument("--app-name", required=True, help="the app's display name (Sam's project list has it)")
        s.add_argument("--morning-at", required=True, help="HH:MM, the morning brief")
        s.add_argument("--evening-at", required=True, help="HH:MM, the evening question. Set it here, not in the app: "
                       "an app-side settings change is a record by you, and the question is skipped on days you wrote")

    s = sub.add_parser("seed")
    story_args(s)
    s.add_argument("--out", required=True)
    s = sub.add_parser("mock")
    story_args(s)
    s.add_argument("--seed-out", required=True, help="docs/seed.example.json")
    s.add_argument("--extra-out", required=True, help="mobile/mock/extra.json")
    s = sub.add_parser("build")
    story_args(s)
    s.add_argument("--port", required=True, type=int)
    s.add_argument("--public-url", required=True, help="https origin for MOJITO_PUBLIC_URL (only used in Web Push links)")
    s.add_argument("--fcm-credentials", required=True,
                   help='Firebase service-account JSON, or "placeholder" (no Android push; the web app does not need it)')
    s.add_argument("--out", required=True)
    for name in ("load", "backdate", "reset", "ask"):
        sub.add_parser(name).add_argument("--out", required=True)
    a = p.parse_args()
    {"seed": cmd_seed, "mock": cmd_mock, "build": cmd_build, "load": cmd_load, "backdate": cmd_backdate,
     "reset": cmd_reset, "ask": cmd_ask}[a.cmd](a)


if __name__ == "__main__":
    main()
